import time as t
import sys
def clear():
    print ('\033[1A' + '\033[K')

print("unnamed~> what is your name?")
username = input(">>")
clear()
print(f"{username}(you)~> {username}")
username = (username + "(you)")
print("unnamed~> what is my name")
name = input(">>")
clear()
print(f"{username}~> {name}")
print(f"{name}~> what country do you live in?")
country = input(">>")
clear()
print(f"{username}~> {country}")
print(f"{name}~> cool! whats it like there?")
input(">>")
clear()
sys.stdout.write(f"{name}~> interesting.")
sys.stdout.flush()
t.sleep(0.5)
sys.stdout.write(".")
sys.stdout.flush()
t.sleep(0.5)
sys.stdout.write(".")
sys.stdout.flush()
t.sleep(0.5)
print()
print()
print("goodbye")
t.sleep(0.5)
